### ISSUE TITLE
Remove Dead and Commented out code and also debug statements

### ISSUE THREAD

**Issue by Sree-Vandana** [Sree-Vandana/CodeReadingAndReview2021#10]
### Rule Description

- Dont leave Unused, Dead and Commented code in the code base. Remove it frequently to keep the code base neat and clean. This include `console.log` statements that are used for debugging.

For **Example** dont do like [PersonalLink.js, line 14](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/PersonLink.js#L14) and [PosterGrid.js, Line 18](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/PosterGrid.js#L18)

### Why it is needed

- Unused, Dead and Commented code increases the file size. It gives the feeling of "Not well maintained code". And this is an issue widely talked about under the name `Code smells`.
- Leaving out unused commented code can increase confusion to new programmers who started working on this codebase.
- Clearing out these unused lines, will help us maintain a good code format, as mentioned in issue #9

**Comment by shashank114** [comment]
Review completed.
This issue can be closed.
