### ISSUE TITLE
Maintain clear code segmentation

### ISSUE THREAD

**Issue by Sree-Vandana** [Sree-Vandana/CodeReadingAndReview2021#13]
### Rule Description

There are different ways we can achieve segmentation within a code and different areas where we need to maintain this segmentation. All these are clearly mentioned below.

**1. Segmentation within a Function**

- Write the code in small segments within a class or a function _(These small segments will perform, a small operation within a big function performing a single task)._ This will help in better and quick understanding of code. within a function. If needed, try to add a comment explaining what those few lines of code do, just like how its mentioned in issue #6 
- A **Good Example** is [App.js, Lines 134, 139, 143, 151, 154, 158, 165 and 169](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/App.js#L134) clearly shows segmentation within a single function, which performs various actions based on user input and each segment is clearly explained using a single line comment.
    
**2. Segmentation in Conditional and loop Statement**

- Have one step indentation where if/ else/ if else() statements are used and no curly brasses are used. The same rule can be applied to loop statements.
- Good example can be

```
if(some Condition){
  _Do Something_
} else if(some Condition) 
    if(some Condition)
      _Do Something_
    else
      _Do Something_
  else
    _Do Something_
```
**3. Add a new empty line in order to maintain clear code segmentation.** A **good example** can be found in [App.js, Lines 134, 139, 143](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/App.js#L134) where each segment has a clear separation using a new empty line.

### Why it is needed

- It is important to have one step indentation where if/ else/ if else() statements are used where curly brasses are not present. Its fine if curly brasses are not used, but show one level of indentation that says that the following statements are present under this else / else if() statement. This gives a clear visual separation of code segments.

- Having a good visual separation in code is important, because When we are looking at a code and trying to figure out what it is doing, most of the time we skim through the code base, skipping some lines of code. This skimming and scanning the code is done more often than we realize it, and sometimes we do it subconsciously. And having a uniform format helps us to easily navigate through the code, understand and also detection of bugs.

- This logical code segmentation can be useful while reading and analyzing the code and any other developer taking a look at the code can easily understand the structure and the code gives a well maintained look.

**Comment by shashank114** [comment]
Review completed.
This issue can be closed.

**Comment by Sree-Vandana** [comment]
Previously did not modify HTML related code to follow the rules. Update that in few files. Closing now.
