### ISSUE TITLE
Handle Errors in the code. (Review)

### ISSUE THREAD

**Issue by Sree-Vandana** [Sree-Vandana/CodeReadingAndReview2021#16]
### Rule Description
_This Rule is already followed in the code base in a sophisticated way. So no need to make changes for this. As it is an important rule, I am going to describe it here and write a review about what is good about it._

In a Web App, the errors can occur any time, we cannot predict them, but we can know where an error might occur. This can be caused when user gives an unexpected input or when the backend API fails to send out response or listen to us. 

- It wont be nice if all the time an error occurs, out app crashes, instead we can handle them and show some statement to the user saying _"Something went wrong, Please try again"_. This would be much better way to deal with errors, rather than displaying the error statement stack, that users doesn't understand.

A **Good Example** of handling Errors is 
- In [TMDBCard.js, Line 9](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/TMDBCard.js#L9) and [TMDBCard.js, Line 42](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/TMDBCard.js#L42) where a state variable is dedicated to store an error occurred in the app. and every time a backend call is made, an if condition is used to capture that error it might throw.
- Not only that, an entire file is dedicated to display different customized error messages to the uses when something goes wrong. **Example**: [NotFound.js](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/NotFound.js) file.

### Why it is needed

- Sometimes input can be abnormal and things might go wrong, and we as programmers are responsible for making sure that our code does what it needs to do, as clearly as possible and write code that is both clean and robust.  

- It is better to throw an exception when we encounter an error, this can make a code base a lot cleaner and based on the error handling statement a programmer can know what the code is dealing with. And also crashes in App does not leave a good impression on users using it.

**Comment by shashank114** [comment]
Review completed.
This issue can be closed.
