### ISSUE TITLE
State Variables and Data structure

### ISSUE THREAD

**Issue by Sree-Vandana** [Sree-Vandana/CodeReadingAndReview2021#19]
### Rule Description

- Always use `const` for all variables and if its value is getting changed anywhere in the code, go back and change it to `let`. 
A **Good Example** can be [DonutChart.js Line 11](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/DonutChart.js#L11), [17](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/DonutChart.js#L17), [23](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/DonutChart.js#L23). Here ratingVal and maxScore values are getting updated in the code, so it is ok to use `let` keyword.
A **Bad example** is [PersonalLink.js Line 13](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/PersonLink.js#L13), [17](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/PersonLink.js#L17), here no need to use let, the variable values are not getting changed anywhere within the code. So we can use `const` keyword.

- Avoid using `var` keyword in java script files, while declaring avariable. 
- As the framework used here is React, it is a good practice to store App state related variable using `useState()` hook.  _(It is good that this code base stored all the variables using `useState` hook and used `const` and `let` variables while storing data that is not related to app state)_

### Why it is needed

- Variables declared using the `var` keyword are either globally or functionally scoped, they do not support block-level scope. This means that if a variable is defined in a loop or in an if statement it can be accessed outside the block and accidentally redefined leading to a buggy program. As a general rule,  _**avoid using the var keyword**._

- `let` keyword is very similar to the var keyword as they both allow us to reassign the value later on. The main difference between the two is that _let deals with a block scope_ and although it can be reassigned it cannot be redeclared.

- `const` keyword is also blocked scoped. However, declaring a variable with the const keyword means that it cannot only be redeclared but also it cannot be reassigned.

**Comment by shashank114** [comment]
Review completed.
This issue can be closed.
