### ISSUE TITLE
Documentation for each file is Needed

### ISSUE THREAD

**Issue by Sree-Vandana** [Sree-Vandana/CodeReadingAndReview2021#5]
### **Rule Description**

Add documentation, describing what the method/ class does. Even though if it is an easily understood method just by glancing at its code, it is advisable to add documentation.

* Use proper and consistent documentation syntax.

  **Example 1:** [App.js, Line 24 ](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/App.js#L24) Comments wont be converted to built documentation. use proper documentation syntax like 
  ```
  /**  
  *What is the functionality of the class/ method
  *@param {<type>} <parameter_name1> - <param1_description>
  *@param {<type>} <parameter_name2> - <param1_description>
  *@returns
  */
  ```

* Dont leave incomplete documentation. 
  This code base is a `React` based Application, contain React class and methods. React class/ method will return a `UI component`. It is better to mention what UI component it is `returns` and what `parameters` it is going to take from outside. _(Example syntax above_) Give a Complete documentation. Dont leave incomplete documentation. Incomplete documentation can be confusing and misleading.

  **Example 2:** Few examples within the code base, where documentation is bad [DonutChart.js, Line 6](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/DonutChart.js#L6). Here in this example the params field is left empty. [Info.js, Line 8](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/Info.js#L8) is an example where the function description is left out. and [Info.js, Line 9](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/Info.js#L9) did not follow above syntax to describe parameters.

* Always use a good library or package to auto-generated documentation.
Here [`JSDoc3`](https://jsdoc.app/) an API documentation generator for JavaScript, similar to Javadoc or phpDocumentor, is added now. The JSDoc tool will scan the source code and generate an HTML documentation website for you.

### **Why it is needed**

- We might not be the only one looking at the code. One of our team mates can look at it, or anyone outside the team may want to built on top of the old code after some years. 

- In this scenario, it is most likely that they go through the automatically generated built documentation, to get a scenes of what the code does. And it is good to have a complete documentation. If there are few methods within the documentation, that are left incomplete, it might look like the code is not well maintained.

- In fact, complete documented code base is mostly likely preferred by developers. **For example,** while selecting any of the libraries or packages within the NodeJS, most developers prefer complete and well documented library/ packages to use within there project.

A good example can be [Java](https://docs.oracle.com/javase/7/docs/api/) and [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript) official documentation, no matter how simple the function is there is a description about it and an example code using that method.

**Comment by Sree-Vandana** [comment]
**Personal Comment**
I am a new member who is working with this code base, that [Shashank](https://github.com/shashank114) previously worked on. Thanks to Shashank, he briefly explained me what each function does, during the meeting. 
But still , he is not available all the time to explain me the functionality. I would prefer to have a documentation for each method in this code base.

**Comment by shashank114** [comment]
Review completed.
This issue can be closed.

**Comment by Sree-Vandana** [comment]
Found a good Java script documentation generator Library in npm [`JSDoc3`](https://jsdoc.app/). Going to add it to the code base to auto generate docs.
