### ISSUE TITLE
Write Small Functions to make the code Understandable

### ISSUE THREAD

**Issue by Sree-Vandana** [Sree-Vandana/CodeReadingAndReview2021#7]
### Rule Description 

- Each function written should tell a story. This makes the functions easier to read and understand. This rule is detailedly mentioned in the book `Clean Code, Chapter 3` and I agree with the author in this, each function should do a small piece of functionality.  

- Function should do one thing, they should do it well and they should do it only.

    **Example** of a very long function is [`Info.js file`](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/Info.js) - In this function, first in `useEffect` all the data from API is being fetched. Then in `return` statement respective UI element is being rendered. 
    This can be simplified, by dedicating this function solely for fetching data, and writing another function to render UI element. 

    _(Other files like [`ListMedia.js`](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/components/ListMedia.js) also show similar behavior, of fetching and rendering UI element, but they did not get so long as this functions in info.js file, which is increasing the vertical length and making it feel like there is so much going on in this function.)_

### Why it is needed

- This not only helps with easy reading but also helps maintain code modularity and understanding. 

- Modifying, maintaining and testing a small block of code with single functionality is much easier than a huge block of code with multiple functionalities.

**Comment by shashank114** [comment]
Review completed.
This issue can be closed.
