### ISSUE TITLE
Maintain Uniform Code Format

### ISSUE THREAD

**Issue by Sree-Vandana** [Sree-Vandana/CodeReadingAndReview2021#9]
### Rule Description

Code Segmentation _(as mentioned in issue #13)_ and formatting mentioned here go hand in hand. There are many similarities to both of these rules, but they differ in few ways. Code segmentation is more like a logical separation of code, where as formatting includes esthetics. So it is better to mention it as a separate rule.

**1. Maintain a good vertical Alignment.** - _Logically related code stays together, this can help with code segmentation within a function. It will be easy to understand._ 
**Example**

    ```
    class ClassName{
      method1(){
        ...
        ...
      }
      method2(){
        ...
      }
    }
    ```

**2. Have uniform Indentation and also uniform function calls,  throughout the code base.**
Helps with code scanning and reading. An example where different function call techniques are used in same file are [App.js, Line 35](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/App.js#L35) which uses arrow function and [App.js, Line 66 to 70](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/App.js#L66) which uses normal call. Always try to maintain uniformity.
https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/App.js#L35 and https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/App.js#L66 

**3. Do not include unnecessary new lines or blank spaces**  - This also includes taking up too many lines to complete a simple operation. 
An example of where a simple operation took too many lines is [App.js, Line 35 ](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/App.js#L35) - _there is no need of open and close brasses for a single line arrow function._ and [App.js, Line 48 ](https://github.com/Sree-Vandana/CodeReadingAndReview2021/blob/ee4779bce9bdea9061aee632109ec145c84b6ead/frontend-web-dev-project-main/frontend-project/src/App.js#L48) - _there is no need extra lines to assign value to a variable._

**4. Write all the Dependent functions at one location** -  Place the callee functions _(also called as helper functions)_ close to each other, above or below of the caller statement or in a separate class altogether. 

### Why it is needed

- Neatly formatted code gives a feeling of well maintained and professionally developed vibe, and this also shows how much of  a clarity the developer has on the code they are working on. 

- A well formatted code helps in understanding and navigating through the code easily.  Every programmer has their own set of formatting styles, so if working in a group, it is best that everyone agree upon a single set of rules and follow them, this helps in maintaining uniformity throughout the code base. 

- When we are looking at a code and trying to figure out what it is doing, most of the time we **_skim_** through the code base, skipping some lines of code. This **_skimming_** and _**scanning**_ the code is done more often than we realize it, and sometimes we do it subconsciously. And having a uniform format helps us to easily navigate through the code, understand and also detect bugs. 

- Once we agree upon some set of rules, we can automate those by changing settings in the IDE we are using.

**Comment by shashank114** [comment]
Review completed.
This issue can be closed.

**Comment by Sree-Vandana** [comment]
Previously did not modify HTML related code to follow the rules. Update that in few files. Closing now.
